#!/bin/bash

set -euo pipefail

pkgs=(
    build-essential
    curl
    gfortran
    git
    libssl-dev
    openssl
    pkg-config
)

pdf_sets=(
    ABMP16als118_5_nnlo
    CT18NNLO
    MSHT20nnlo_as118
    MSHT20qed_nnlo
    NNPDF31_nlo_as_0118_luxqed
    NNPDF40_nlo_as_01180
    NNPDF40_nlo_pch_as_01180
    NNPDF40_nnlo_as_01180
    NNPDFpol11_100
    MAPFF10NLOPIsum
)

add_pdf_set_urls=(
    # Tanjona's polarized PDF set
    "https://data.nnpdf.science/pineappl/pdfs/240608-tr-pol-nlo-100.tar.gz"
)

apt update
apt install -y "${pkgs[@]}"

# install rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y

for version in ${RUST_V}; do
    # the last command will be the default
    rustup install "${version}" --profile minimal
    rustup default "${version}"
    # install LLVM tools needed for code coverage
    rustup component add llvm-tools
done

# install cargo-c needed for the CAPI
cargo install --locked cargo-c --version "${CARGOC_V}" --features=vendored-openssl

# remove files generated by cargo
rm -r /usr/local/cargo/registry

# create this directory manually since we install LHAPDF later
mkdir -p /usr/local/share/LHAPDF

# create array with all PDF URLs
declare -a pdf_set_urls
for pdf in "${pdf_sets[@]}"; do
    pdf_set_urls+=( "https://lhapdfsets.web.cern.ch/current/${pdf}.tar.gz" )
done
pdf_set_urls+=( "${add_pdf_set_urls[@]}" )

# install PDF sets
for url in "${pdf_set_urls[@]}"; do
    # see the following link why `--no-same-owner` may be necessary:
    # https://github.com/habitat-sh/builder/issues/365#issuecomment-382862233
    curl -fsSL "${url}" | tar xzf - --no-same-owner -C /usr/local/share/LHAPDF
done

static=no /tmp/install-cli-dependencies.sh
