# .github/actions/cache-test-data/action.yml

name: Cache Test Data
description: Caches and downloads test data
runs:
  using: "composite"
  steps:
    - name: Cache test data
      id: cache
      uses: actions/cache@v4
      with:
        path: test-data
        key: test-data-v23
    - name: Download test data if cache miss
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd maintainer
        ./download-test-data.sh
      shell: bash
