version: 2

sphinx:
  builder: html
  configuration: pineappl_py/docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    rust: "1.61"

python:
  install:
    - method: pip
      path: pineappl_py
      extra_requirements:
        - docs
