version: 2

sphinx:
    builder: html
    configuration: pineappl_py/doc/source/conf.py

python:
    version: 3.7
    install:
        - method: pip
          path: pineappl_py
#          extra_requirements:
#              - docs
    - requirements: pineappl_py/dev.requirements.txt
