version: 2

sphinx:
  builder: html
  configuration: pineappl_py/docs/source/conf.py

python:
  install:
    - requirements: pineappl_py/dev.requirements.txt
    # this is fake (see conf.py) but, I think, unavoidable
    - method: pip
      path: pineappl_py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    rust: "1.55"
