version: 2

sphinx:
  builder: html
  configuration: pineappl_py/docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    rust: "1.55"
  jobs:
    pre_install: 
      - pip config unset global.use-feature
      - pip config unset --site global.use-feature
      - pip config list

python:
  install:
    - method: pip
      path: pineappl_py
      extra_requirements:
        - docs
