version: 2

sphinx:
    builder: html
    configuration: pineappl_py/doc/source/conf.py

python:
    version: 3.7
    install:
        - requirements: pineappl_py/dev.requirements.txt
        - method: pip
          path: pineappl_py

build:
    apt_packages:
        - rustc
        - cargo

#conda:
#    environment: pineappl_py/environment.yml
