version: 2

sphinx:
    builder: html
    configuration: pineappl_py/doc/source/conf.py

python:
    version: 3.7
    install:
        - requirements: pineappl_py/dev.requirements.txt
        # this is fake (see conf.py) but, I think, unavoidable
        - method: pip
          path: pineappl_py

build:
    apt_packages:
        - rustc
        - cargo
