#!/bin/bash

set -euo pipefail

if [[ ! -x $(command -v maturin) ]]; then
    echo "Didn't find the \`maturin\` binary."
    exit 1
fi

# TODO: check that maturin's version is larger than TODO

maturin generate-ci github --manifest-path pineappl_py/Cargo.toml > .github/workflows/wheels.yml

# TODO: using `patch` is very fragile
patch -p1 < <(cat <<EOF
--- a/.github/workflows/wheels.yml
+++ b/.github/workflows/wheels.yml
@@ -4,13 +4,8 @@
 #    maturin generate-ci github --manifest-path pineappl_py/Cargo.toml
 #
 on:
-  push:
-    branches:
-      - main
-      - master
-    tags:
-      - '*'
-  pull_request:
+  release:
+    types: [published]
   workflow_dispatch:
 
 permissions:
EOF
)

# - select a subset of architectures that we're interested in
# - make it visible that we modified the script
# - our secret taken has a different name
# - assign a suitable name to the workflow
sed -i \
    -e 's/target: \[x86_64, x86, aarch64, armv7, s390x, ppc64le\]/target: [x86_64]/' \
    -e 's/target: \[x64, x86\]/target: [x64]/' \
    -e 's/target: \[x86_64, aarch64\]/target: [universal2-apple-darwin]/' \
    -e 's/\(Generated by maturin v[.0-9]\+\)/\1 and modified by update-wheels-ci.sh/' \
    -e 's/PYPI_API_TOKEN/PYPI_TOKEN/' \
    -e 's/^on:/name: Wheels\n\n\0/' \
    -e "s/python-version: '3.10'/python-version: |\n            3.7\n            3.8\n            3.9\n            3.10\n            3.11/" \
    .github/workflows/wheels.yml
