#!/bin/bash

set -euo pipefail

if [[ ! -x $(command -v maturin) ]]; then
    echo "Didn't find the \`maturin\` binary."
    exit 1
fi

# TODO: check that maturin's version is larger than TODO

maturin generate-ci github --manifest-path pineappl_py/Cargo.toml > .github/workflows/wheels.yml

patch -p1 < <(cat <<EOF
--- old/.github/workflows/wheels.yml	2023-03-02 14:32:36.788761704 +0000
+++ new/.github/workflows/wheels.yml	2023-03-02 14:34:52.335533289 +0000
@@ -1,11 +1,7 @@
 # Generated by maturin v0.14.14
 on:
-  push:
-    branches:
-      - main
-      - master
-  pull_request:
-  workflow_dispatch:
+  release:
+    types: [published]
 
 jobs:
   linux:
EOF
)

# - select a subset of architectures that we're interested in
# - make it visible that we modified the script
# - our secret taken has a different name
# - add push event, even if it won't trigger an actual release
# - and make sure it only runs on releases
sed -i \
    -e 's/target: \[x86_64, x86, aarch64, armv7, s390x, ppc64le\]/target: [x86_64]/' \
    -e 's/target: \[x64, x86\]/target: [x64]/' \
    -e 's/target: \[x86_64, aarch64\]/target: [universal2-apple-darwin]/' \
    -e 's/\(Generated by maturin v[.0-9]\+\)/\1 and modified by update-wheels-ci.sh/' \
    -e 's/PYPI_API_TOKEN/PYPI_TOKEN/' \
    -e 's/\(types: \[published\]\)/\1\n  push:/' \
    -e "s/\"startsWith(.*)\"/\"startsWith(github.event, 'release')\"/" \
    -e "s/python-version: '3.10'/python-version: |\n            3.7\n            3.8\n            3.9\n            3.10\n            3.11/" \
    .github/workflows/wheels.yml
