[package]
name = "pineappl_applgrid"
version = "0.1.0"
authors = ["Christopher Schwan <handgranaten-herbert@posteo.de>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/N3PDF/pineappl"
readme = "README.md"
keywords = ["high-energy-physics", "physics"]
categories = ["science"]
description = "PineAPPL's interface to APPLgrid"
rust-version = "1.56.1"

[dependencies]
cxx = "1.0.65"

[build-dependencies]
cxx-build = "1.0.65"
