#!/bin/bash

set -euo pipefail

pkgs=(
    build-essential
    curl
    gfortran
    git
    libssl-dev
    openssl
    pkg-config
)

pdf_sets=(
    ABMP16als118_5_nnlo
    CT18NNLO
    MSHT20nnlo_as118
    MSHT20qed_nnlo
    NNPDF31_nlo_as_0118_luxqed
    NNPDF40_nlo_as_01180
    NNPDF40_nlo_pch_as_01180
    NNPDF40_nnlo_as_01180
    NNPDFpol11_100
    MAPFF10NLOPIsum
)

apt update
apt install -y "${pkgs[@]}"

# install rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y

for version in ${RUST_V}; do
    # the last command will be the default
    rustup install "${version}" --profile minimal
    rustup default "${version}"
    # install LLVM tools needed for code coverage
    rustup component add llvm-tools
done

# install cargo-c needed for the CAPI
cargo install --locked cargo-c --version "${CARGOC_V}"

# remove files generated by cargo
rm -r /usr/local/cargo/registry

# create this directory manually since we install LHAPDF later
mkdir -p /usr/local/share/LHAPDF

# install PDF sets
for pdf in "${pdf_sets[@]}"; do
    # see the following link why `--no-same-owner` may be necessary:
    # https://github.com/habitat-sh/builder/issues/365#issuecomment-382862233
    curl -fsSL "https://lhapdfsets.web.cern.ch/current/${pdf}.tar.gz" | tar xzf - --no-same-owner -C /usr/local/share/LHAPDF
done

# install Tanjona's polarized PDF set
curl -fsSL "https://data.nnpdf.science/pineappl/pdfs/240608-tr-pol-nlo-100.tar.gz" | tar xzf - --no-same-owner -C /usr/local/share/LHAPDF

static=no /tmp/install-cli-dependencies.sh
