FROM quay.io/pypa/manylinux2014_x86_64

ARG MATURIN_TAR='maturin-x86_64-unknown-linux-musl.tar.gz'
ARG MATURIN_TAG='v0.13.0-beta.9'
ARG LHAPDF_URL='https://lhapdf.hepforge.org/downloads/?f='
ARG LHAPDF_TAG='LHAPDF-6.5.3'

# install c compiler
# and create a dedicated user
RUN /bin/bash -c "yum install gcc -y; \
                  useradd -m pineappl;\
                  su - pineappl"

ARG USER=pineappl
USER ${USER}
ENV PATH=/home/${USER}/local/bin:/home/${USER}/.cargo/bin:${PATH}
ENV PKG_CONFIG_PATH=/home/${USER}/local/lib/pkgconfig:PKG_CONFIG_PATH
ENV LD_LIBRARY_PATH=/home/${USER}/local/lib:LD_LIBRARY_PATH

# install dependencies
# - rust
# - maturin
RUN /bin/bash -c "cd ${HOME}; \
                  mkdir -p local/bin; \
                  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y; \
                  curl --remote-name -L https://github.com/PyO3/maturin/releases/download/${MATURIN_TAG}/${MATURIN_TAR}; \
                  tar -xvzf ${MATURIN_TAR} --directory=local/bin/; \
                  curl -L ${LHAPDF_URL}${LHAPDF_TAG}.tar.gz > LHAPDF.tar.gz; \
                  tar xvzf LHAPDF.tar.gz; \
                  cd ${LHAPDF_TAG}; ./configure --disable-python --prefix=${HOME}/local; make && make install"
