FROM quay.io/pypa/manylinux2014_x86_64

ARG MATURIN_TAR='maturin-x86_64-unknown-linux-musl.tar.gz'
ARG MATURIN_TAG='v0.13.0-beta.9'

# install c compiler
# and create a dedicated user
RUN /bin/bash -c "yum install gcc -y; \
                  useradd -m pineappl;\
                  su - pineappl"

USER pineappl

# install dependencies
# - rust
# - maturin
RUN /bin/bash -c "cd ${HOME}; \
                  mkdir -p local/bin; \
                  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y; \
                  curl --remote-name -L https://github.com/PyO3/maturin/releases/download/${MATURIN_TAG}/${MATURIN_TAR}; \
                  tar -xvzf ${MATURIN_TAR} --directory=local/bin/"

COPY maturin /home/pineappl

ENTRYPOINT ["/home/pineappl/maturin"]
# To minimize the size of the wheel use '--strip'
CMD ["build --release --interpreter 3.7 3.8 3.9 3.10 pypy3.7"]
