FROM quay.io/pypa/manylinux2014_x86_64

ARG MATURIN_TAR='maturin-x86_64-unknown-linux-musl.tar.gz'
ARG MATURIN_TAG='v0.11.3'

RUN /bin/bash -c "yum install gcc -y; \
                  cd /root; \
                  mkdir -p local/bin; \
                  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y; \
                  curl --remote-name -L https://github.com/PyO3/maturin/releases/download/${MATURIN_TAG}/${MATURIN_TAR}; \
                  tar -xvzf ${MATURIN_TAR} --directory=local/bin/"

COPY maturin /

ENTRYPOINT ["/maturin"]
# To minimize the size of the wheel use '--strip'
CMD ["build --release"]
