#!/bin/bash
export PATH=${HOME}/local/bin:${HOME}/.cargo/bin:${PATH}
cd ${HOME}
# clone pineappl code
git clone https://github.com/NNPDF/pineappl.git
# compile pineappl python package
cd pineappl/pineappl_py
maturin $@
