name: CAPI

on: push

jobs:
  capi:
    runs-on: ubuntu-latest
    container: ghcr.io/nnpdf/pineappl-ci:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PineAPPL's C API
        run: |
          cargo cinstall --verbose --prefix=/usr/local/ --manifest-path pineappl_capi/Cargo.toml
          ldconfig

      - name: Test C example
        run: |
          cd examples/basic-capi-usage
          make
          ./dyaa
          test -f ./DY-LO-AA.pineappl.lz4

      - name: Test Fortran example
        run: |
          cd examples/fortran
          make
          ./dyaa
          test -f ./DY-LO-AA.pineappl.lz4

      - name: Test C++ example
        run: |
          cd examples/object-oriented-cpp
          make
          ./dyaa
          test -f ./DY-LO-AA.pineappl.lz4

  linux:
    runs-on: ubuntu-20.04
    container: ghcr.io/nnpdf/pineappl-ci:latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd pineappl_capi
          cargo cinstall --verbose --destdir=/tmp/capi-destdir --library-type=cdylib --prefix=/ --target=${{ matrix.target }}
      - name: Upload libraries
        uses: actions/upload-artifact@v3
        with:
          name: libpineappl_capi-${{ matrix.target }}
          path: /tmp/capi-destdir/
