name: CAPI

on:
  push:
    branches-ignore:
      - pycli
      - update-container-2

env:
  # our GLIBC version is too old to support Node 20:
  # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  capi:
    runs-on: ubuntu-latest
    container: ghcr.io/nnpdf/pineappl-ci:latest
    steps:
      # checkout@v4 uses a newer version of Node that's incompatible with our container's GLIBC
      - uses: actions/checkout@v3

      - name: Install PineAPPL's C API
        run: |
          export RUSTFLAGS="-Cinstrument-coverage"
          cargo cinstall --verbose --prefix=/usr/local/ --manifest-path pineappl_capi/Cargo.toml
          ldconfig

      - name: Test C++ example
        run: |
          cd examples/cpp
          # if `make` is too old, it doesn't support the `!=` operator
          sed -i "s/\([a-zA-Z_]\+\) != \(.*\)$/echo \1 = \$(\2)/e" Makefile
          make test-examples

      - name: Test Fortran example
        run: |
          cd examples/fortran
          sed -i "s/\([a-zA-Z_]\+\) != \(.*\)$/echo \1 = \$(\2)/e" Makefile
          make
          ./dyaa
          test -f ./DY-LO-AA.pineappl.lz4

      - name: Test OO C++ example
        run: |
          cd examples/object-oriented-cpp
          sed -i "s/\([a-zA-Z_]\+\) != \(.*\)$/echo \1 = \$(\2)/e" Makefile
          make
          ./dyaa
          test -f ./DY-LO-AA.pineappl.lz4

      - name: Generate code coverage
        run: |
          find . -name '*.profraw' -exec $(rustc --print target-libdir)/../bin/llvm-profdata merge -sparse -o pineappl.profdata {} +
          $(rustc --print target-libdir)/../bin/llvm-cov export \
                  --ignore-filename-regex='index.crates.io' \
                  --ignore-filename-regex='rustc' \
                  --instr-profile=pineappl.profdata \
                  --skip-functions \
                  --object /usr/local/lib/libpineappl_capi.so.*.*.* \
                  --format lcov > lcov.info
          # print all files for which coverage has been generated
          grep SF lcov.info | sort -u | sed 's/SF://'

      - name: Upload to codecov.io
        # version 3.1.5 upgrades to Node 20 (https://github.com/codecov/codecov-action/issues/1230), which breaks inside our container
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: capi
