name: Publish CLI wheels

on:
  push:
    # tags:
    #   - "v[0-9]+*"
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  wheels-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64]
    # if: false    defaults:
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            gcc
            make
            autoconf
            python3
            curl
            tar
            pkgconf
      - uses: actions/setup-python@v5
        with:
          # WARNING: be careful with the ordering - the last version is the
          # default one. Apparently maturin doesn't find all Python versions
          # when one chooses a PyPy version instead of CPython as default
          python-version: |
            pypy3.7
            pypy3.8
            pypy3.9
            pypy3.10
            3.7
            3.8
            3.9
            3.11
            3.12
            3.10
      - name: Install LHAPDF
        run: |
          curl "https://lhapdf.hepforge.org/downloads/?f=LHAPDF-6.5.4.tar.gz" | tar xzf -
          cd LHAPDF-6.5.4
          # compiling with Python gives errors, but we also don't need Python
          ./configure --disable-python
          make -j
          make install
          # print the path of `pkgconf`
          command -v pkgconf
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter --manifest-path pineappl_cli/Cargo.toml
          sccache: "true"
      - name: Patch wheels
        run: |
          delvewheel repair dist/*
          python3 maintainer/patch_binary_wheel.py dist/*
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-${{ matrix.target }}
          path: dist
