name: Crates

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Publish all crates
      if: "startsWith(github.ref, 'refs/tags/')"
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        # this must be at least Rust 1.66 to support waiting for dependencies to on crates.io:
        # https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-166-2022-12-15
        rustup default stable
        cd pineappl
        cargo publish
        cd ../pineappl_applgrid
        cargo publish
        cd ../pineappl_fastnlo
        cargo publish
        cd ../pineappl_capi
        cargo publish
        cd ../pineappl_cli
        cargo publish
