name: Download/Cache Test Data
on:
  workflow_call:
    # If needed downstream
    outputs:
      cache-hit:
        description: "Whether cache was hit"
        value: ${{ jobs.cache-test.outputs.cache-hit }}

jobs:
  cache-test:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-test-data.outputs.cache-hit }}
    steps:
      - name: Cache test data
        id: cache-test-data
        uses: actions/cache@v4
        with:
          path: test-data
          key: test-data-v20

      - name: Download test data if cache miss
        if: steps.cache-test-data.outputs.cache-hit != 'true'
        run: |
          cd maintainer
          ./download-test-data.sh
