on:
  workflow_call:

jobs:
  lhapdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set environment variables
        run: |
          echo "${HOME}/prefix/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${HOME}/prefix/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=${HOME}/prefix/lib/pkgconfig" >> $GITHUB_ENV
          echo "PYTHONPATH=${HOME}/prefix/lib/python3.7/site-packages" >> $GITHUB_ENV
      - name: Install LHAPDF 6.4.0
        env:
          VERSION: 6.4.0
        run: |
          wget --no-verbose https://lhapdf.hepforge.org/downloads/?f=LHAPDF-${VERSION}.tar.gz -O LHAPDF-${VERSION}.tar.gz
          tar xzf LHAPDF-${VERSION}.tar.gz
          cd LHAPDF-${VERSION}
          ./configure --prefix=${HOME}/prefix --disable-static
          make -j
          make install
      - name: Install PDF sets
        run : |
          lhapdf update
          lhapdf install NNPDF31_nlo_as_0118_luxqed
          lhapdf install NNPDF40_nnlo_as_01180
