on: [push]

jobs:
  macos-capi:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin]
    steps:
      - uses: actions/checkout@v3
      - name: Compile library
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          cargo install cargo-c
          cd pineappl_capi
          cargo cinstall --verbose --destdir=prefix --library-type=cdylib --prefix=/ --target=${{ matrix.target }}
          cd prefix
          tar czf ../../pineappl_capi-${{ matrix.target }}.tar.gz .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pineappl_capi-${{ matrix.target }}
          path: pineappl_capi-${{ matrix.target }}.tar.gz
