name: MSRV

on:
  push:
    branches-ignore:
      - pycli
      - bump-pyo3-version

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/nnpdf/pineappl-ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run check
        run: |
          # extract the MSRV
          MSRV=$(grep '^rust-version ' Cargo.toml | cut -d= -f2- | tr -d ' "')
          # enable the MSRV
          rustup default "${MSRV}"
          cargo check --all-features --all-targets
