name: MSRV

on:
  push:
    branches-ignore:
      - pycli

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/nnpdf/pineappl-ci:latest
    steps:
      # checkout@v4 uses a newer version of Node that's incompatible with our container's GLIBC
      - uses: actions/checkout@v3

      - name: Run check
        run: |
          # enable the MSRV
          rustup default 1.70.0
          cargo check --all-features --all-targets
