name: MSRV

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/nnpdf/pineappl-ci:latest
    steps:
    - uses: actions/checkout@v4

    - name: Run check
      run: |
        # enable the MSRV
        rustup default 1.64.0
        cargo check --all-features --all-targets
