name: MSRV

on:
  push:
    branches-ignore:
      - pycli
      - bump-pyo3-version

env:
  CARGO_TERM_COLOR: always
  # our GLIBC version is too old to support Node 20:
  # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/nnpdf/pineappl-ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run check
        run: |
          # enable the MSRV
          rustup default 1.70.0
          cargo check --all-features --all-targets
