name: Python

on:
  push:
    branches-ignore:
      - pycli

jobs:
  test:
    # `ubuntu-24.04` doesn't support Python 3.7 anymore
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        env:
          # `-C link-dead-code` is needed to prevent 'warning: XX functions have mismatched data' warnings
          RUSTFLAGS: '-Cinstrument-coverage -Clink-dead-code'
        run: |
          cd pineappl_py
          python -m venv env
          . env/bin/activate
          pip install maturin
          maturin develop --extras test
          pytest
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: pineappl_py/coverage.xml
          flags: python
