name: Python

on:
  push:
    branches-ignore:
      - pycli

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
          rustup install stable --profile minimal
          rustup default stable
          rustup component add llvm-tools
      - name: Test
        env:
          RUSTFLAGS: '-Cinstrument-coverage'
        run: |
          cd pineappl_py
          python -m venv env
          . env/bin/activate
          pip install maturin
          maturin develop --extras test
          pytest
          find . -name '*.profraw' -exec $(rustc --print target-libdir)/../bin/llvm-profdata merge -sparse -o pineappl.profdata {} +
          $(rustc --print target-libdir)/../bin/llvm-cov export \
              --ignore-filename-regex=index.crates.io \
              --ignore-filename-regex=rustc \
              --instr-profile=pineappl.profdata \
              --skip-functions \
              --object env/lib/python*/site-packages/pineappl/pineappl.*.so \
              --format lcov > lcov.info
          # print all files for which coverage has been generated
          grep SF lcov.info | sort -u | sed 's/SF://'
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: pineappl_py/lcov.info
          flags: python
