name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/cache@v2
      id: cache-lhapdf
      with:
        path: ~/prefix
        key: ${{ runner.os }}-lhapdf-${{ hashFiles('prefix/**') }}
    - name: Set LHAPDF paths
      run: |
        echo "${HOME}/prefix/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${HOME}/prefix/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${HOME}/prefix/lib/pkgconfig" >> $GITHUB_ENV
        echo "PYTHONPATH=${HOME}/prefix/lib/python3.7/site-packages" >> $GITHUB_ENV
    - name: Install LHAPDF 6.3.0
      if: steps.cache-lhapdf.outputs.cache-hit != 'true'
      run: |
        wget 'https://lhapdf.hepforge.org/downloads/?f=LHAPDF-6.3.0.tar.gz' -O LHAPDF-6.3.0.tar.gz
        tar xzf LHAPDF-6.3.0.tar.gz
        cd LHAPDF-6.3.0
        ./configure --prefix=${HOME}/prefix
        make -j
        make install
        lhapdf install NNPDF31_nlo_as_0118_luxqed
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          default: true
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --verbose
    - name: Build CLI
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path pineappl_cli/Cargo.toml
    - name: Generate doctest coverage
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: --workspace --exclude pineappl_capi --exclude-files pineappl_py/* --ignore-tests
        run-types: Doctests,Tests
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
    - name: Install cargo-c
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-c
    - name: Install PineAPPL's C API
      run: |
        ls -alR $HOME/prefix
        cargo cinstall -vv --prefix=$HOME/prefix --manifest-path pineappl_capi/Cargo.toml
    - name: Test C++ example
      run: |
        cd examples/cpp
        make
        ./dyaa
        test -f ./DY-LO-AA.pineappl
