name: Python publication

on:
  release:
    # run only on published, not for drafts
    types: [published]

jobs:
  deploy-linux:
    runs-on: ubuntu-latest
    # a dedicated container is needed, so maturin-action is not an option, see pineappl_py/package/README.md for details
    container:
      image: docker://ghcr.io/n3pdf/maturin:0.2.1
    steps:
      - name: Compile and Publish wheels
        working-directory: /home/pineappl
        env:
          HOME: /home/pineappl
        run: |
          ~/maturin publish --skip-existing --username __token__ --password ${{ secrets.PYPI_TOKEN }}

  deploy-other:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            flags: --universal2
          - os: windows-latest
            flags: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: messense/maturin-action@v1
        with:
          maturin-version: latest
          command: publish
          args: --manifest-path pineappl_py/Cargo.toml ${{ matrix.flags }} --skip-existing --username __token__ --password ${{ secrets.PYPI_TOKEN }}
