name: Python publication

on: [workflow_dispatch]
  # release:
    # run only on published, not for drafts
    # types: [published]

jobs:
  deploy-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Compile and Publish wheels
        uses: docker://ghcr.io/n3pdf/maturin:latest
        with:
          # args: publish --skip-existing --username N3PDF --password ${{ secrets.PYPI_PWD }}
          args: publish --skip-existing --username N3PDF-ac --password ${{ secrets.PYPI_PWD }} -r https://test.pypi.org/legacy/

  deploy-macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: messense/maturin-action@v1
        with:
          maturin-version: latest
          command: publish
          # args: --universal2 --skip-existing --username N3PDF --password ${{ secrets.PYPI_PWD }}
          args: --universal2 --skip-existing --username N3PDF-ac --password ${{ secrets.PYPI_PWD }} -r https://test.pypi.org/legacy/
